# Generated by Django 5.2.8 on 2025-11-22 06:48

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for this connection.', max_length=100, unique=True)),
                ('db_type', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL')], default='POSTGRES', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
