# Generated by Django 5.2.8 on 2025-11-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='db_name',
            field=models.CharField(default='UNKNOWN_DB', max_length=100),
            preserve_default=False,
        ),
    ]
